pager_for_content_type_settings.settings:
  type: config_object
  label: 'Pager for content type settings'
  mapping:
    pager_for_content_type_previous_text:
      type: string
      label: '"Previous" text'
    pager_for_content_type_next_text:
      type: string
      label: '"Next" text'
